
CREATE TABLE `device` (
	`idDevice` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`streamName0` VARCHAR(255) NULL DEFAULT NULL,
	`streamName1` VARCHAR(255) NULL DEFAULT NULL,
	`streamName2` VARCHAR(255) NULL DEFAULT NULL,
	`streamName3` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`idDevice`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `measure` (
	`idMeasure` INT(11) NOT NULL AUTO_INCREMENT,
	`time` DATETIME NULL DEFAULT NULL,
	`idDevice` INT(11) NULL DEFAULT NULL,
	`stream0` FLOAT NULL DEFAULT NULL,
	`stream1` FLOAT NULL DEFAULT NULL,
	`stream2` FLOAT NULL DEFAULT NULL,
	`stream3` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`idMeasure`),
	INDEX `FK9B263D3E29260516` (`idDevice`),
	INDEX `Indice 3` (`idDevice`, `time`),
	CONSTRAINT `FK9B263D3E29260516` FOREIGN KEY (`idDevice`) REFERENCES `device` (`idDevice`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

